### PR TITLE
Beyond Compare settings

### PR DESCRIPTION
**Pull request by floq-design**
Hi
Added Beyond Compare (tested with v4) settings to the app templates.
Cheers
James

### CODE REVIEW

**Comment by colinta** [comment]
Cool, thanks!  Are all these changes just from `\r\n` vs `\n`?  You might consider setting `git config --global core.autocrlf true`, or maybe `input`.  I wish Windows had given up this fight and gone with `\n` - *sigh* such a stupid point of contention.

Anyway, I'm merging, but I'm gonna re-save and re-commit this file so the line endings are consistent.

**Comment by colinta** [comment]
Nevermind, I think you actually *fixed* these line endings.  Looks like the current file uses `\n`, as desired.

Thanks!

**Comment by floq-design** [comment]
I editted the file in SublimeText on a Mac - the app line-ending preference is:

`// Determines what character(s) are used to terminate each line in new files.`
`// Valid values are 'system' (whatever the OS uses), 'windows' (CRLF) and`
`// 'unix' (LF only).`
`"default_line_ending": "system",`

Not sure how to find out what it's using - I imagine it's the 'unix' LF only...

**Comment by colinta** [comment]
Yeah I think it must have had `\r\n` *before* you edited it - I just noticed that all the lines were changed, and assumed it was changing `\n` to `\r\n`.  But yeah, I checked it, it looks correct.

**Pull request merged**
